### ISSUE TITLE
pdm_scorer._calculate_progress() returns negative target if progress along centerline is negative

### ISSUE THREAD

**Issue by shgd95** [autonomousvision/tuplan_garage#61] opened 2024-11-27 11:19 UTC
In _calculate_progress() of the
[PDM scorer](https://github.com/autonomousvision/tuplan_garage/blob/main/tuplan_garage/planning/simulation/planner/pdm_planner/scoring/pdm_scorer.py
), trajectories that make negative progress along the centerline, lead to negative targets, which causes errors when training with BCE loss.
The issue can be fixed by replacing line 509
self._progress_raw = progress_in_meter
with
self._progress_raw = np.clip(progress_in_meter, a_min=0, a_max=None) .

I saw that the same thing was already done in [NAVSIM](https://github.com/autonomousvision/navsim/blob/main/navsim/planning/simulation/planner/pdm_planner/scoring/pdm_scorer.py
), line 412.

Thanks for your great work! Great codebase to build upon.

**Comment by DanielDauner** [comment] 2024-11-28 08:45
Hi Steffen,

Thanks for pointing this out! I tested that clipping the unnormalized progress does not lead to any differences in the PDM-Closed results and pushed the changes. There are several implementation differences between PDM-Closed in NAVSIM vs. this repo, which might matter if you want to use more general proposals and a BCE loss to predict the subscores. 

For example, the NAVSIM version has a different drivable area map, which considers roadblock, intersection, and parking area polygons. The “original” PDM-Closed considered only lane, lane-connector, and parking area polygons, which can lead to issues, as parallel lanes often have small gaps in between (resulting in false positive off-road infractions). Also note that the driving direction metric is slightly different and that the progress score is set to 0 for multiplier infractions before selecting a proposal to normalize the progress ([here](https://github.com/autonomousvision/tuplan_garage/blob/main/tuplan_garage/planning/simulation/planner/pdm_planner/scoring/pdm_scorer.py#L175C1-L176C73)). 

I am hesitant to change certain implementation details of PDM-Closed to leave the numbers of the CoRL paper reproducible. If you have any questions, feel free to answer this issue or email me.

Best,
Daniel

**Closed as completed by DanielDauner** 2024-11-28 08:45 UTC

**Comment by z-suri** [comment] 2025-07-28 09:14
Hi @DanielDauner, you mentioned, the original PDM only sees lane centerlines. But, after looking at some of the results, I want to understand, how it is able to stop and start correctly from a stop traffic signal. For e.g. 

5e8c626551b15567
![Image](https://github.com/user-attachments/assets/9214043c-7d0d-408b-84ca-8b397f67472e)

This is not always the case though. Most failures happen because it ignores the traffic lights.

**Comment by DanielDauner** [comment] 2025-07-28 09:41
Hi @z-suri, 

The traffic lights are added as stationary objects into the [`PDMObservation`](https://github.com/autonomousvision/tuplan_garage/blob/main/tuplan_garage/planning/simulation/planner/pdm_planner/observation/pdm_observation.py#L197) (i.e. the occupancy map for IDM). The traffic lights in nuPlan are somewhat noisy. I think in some cases the traffic lights are also ignored, if the ego agent is already fully on the intersection. I don't know the details from the top of my head.

Hope that helps! 
Daniel
