### ISSUE TITLE
AssertionError in evaluation

### ISSUE THREAD

**Issue by Shuijing725** [autonomousvision/tuplan_garage#8] opened 2023-07-25 17:57 UTC
Hi,

When I evaluate pdm_closed_planner and pdm_open_planner in closed loop, non reactive agent setting, both planners runs fine without error if I use a reduced scenario filter (with 3 or 5 scenarios randomly picked from the validation dataset). However, in **val14_split**, when running
```
python $NUPLAN_DEVKIT_ROOT/nuplan/planning/script/run_simulation.py +simulation=closed_loop_nonreactive_agents planner=pdm_closed_planner scenario_filter=val14_split scenario_builder=nuplan worker=single_machine_thread_pool scenario_builder.data_root=/fs/scratch/projects/proj-ai-planning/archive/nuScenes/nuplan/dataset/nuplan-v1.1/splits/val hydra.searchpath="[pkg://nuplan_garage.planning.script.config.common, pkg://nuplan_garage.planning.script.config.simulation, pkg://nuplan.planning.script.config.common, pkg://nuplan.planning.script.experiments]"
```
I get the following error when the simulations are being executed:
```
Traceback (most recent call last):
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/metrics/metric_engine.py", line 112, in compute_metric_results
    metric_results[metric.name] = metric.compute(history, scenario=scenario)
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/metrics/evaluation_metrics/common/speed_limit_compliance.py", line 218, in compute
    time_series = TimeSeries(
  File "<string>", line 7, in __init__
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/metrics/metric_result.py", line 127, in __post_init__
    assert len(self.time_stamps) == len(self.values)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/runner/executor.py", line 27, in run_simulation
    return sim_runner.run()
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/runner/simulations_runner.py", line 128, in run
    self.simulation.callback.on_simulation_end(self.simulation.setup, self.planner, self.simulation.history)
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/callback/multi_callback.py", line 68, in on_simulation_end
    callback.on_simulation_end(setup, planner, history)
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/callback/metric_callback.py", line 102, in on_simulation_end
    run_metric_engine(
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/callback/metric_callback.py", line 24, in run_metric_engine
    metric_files = metric_engine.compute(history, scenario=scenario, planner_name=planner_name)
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/metrics/metric_engine.py", line 133, in compute
    all_metrics_results = self.compute_metric_results(history=history, scenario=scenario)
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/metrics/metric_engine.py", line 119, in compute_metric_results
    raise RuntimeError(f"Metric Engine failed with: {e}")
RuntimeError: Metric Engine failed with: 
Traceback (most recent call last):
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/metrics/metric_engine.py", line 112, in compute_metric_results
    metric_results[metric.name] = metric.compute(history, scenario=scenario)
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/metrics/evaluation_metrics/common/speed_limit_compliance.py", line 218, in compute
    time_series = TimeSeries(
  File "<string>", line 7, in __init__
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/metrics/metric_result.py", line 127, in __post_init__
    assert len(self.time_stamps) == len(self.values)
AssertionError
```

**Comment by DanielDauner** [comment] 2023-07-25 19:26
I am currently not able to reproduce this issue. Does the assertion error occur instantly or after all scenarios have been simulated? Can you narrow it down to a scenario token where the error occurs?

**Comment by mh0797** [comment] 2023-07-26 06:04
Hi @Shuijing725,
First of all, thank you for using the nuPlan Garage.
Regarding your issue: I am trying to reproduce the issue on our side. 
Can you provide us with more information on how to reproduce the issue:
* Which version of the nuPlan devkit are you using?
* Does the error occur during or after the simulations (during metric aggregation)?
* Does the error occur only with a specific scenario token? If so, please provide us with the exact token

**Comment by Shuijing725** [comment] 2023-07-26 06:46
Hi @mh0797,

Thank you for your response. To answer your questions:
- 1.2.2.
- I'm not sure because I'm new to nuplan. It appears in the metric engine code after the message "Starting 1118 simulations using..." is printed. The full error trace is shown below.
- In the error trace below, multiple tokens are mentioned. Inside the trace, the mentioned [log, token] pairs are
  - [2021.07.24.23.59.52_veh-12_04767_05924, 05f93c480c1d5984]
  - [2021.07.24.00.36.59_veh-47_05600_06769, 011d97b0e5a85f5f]
  - [2021.07.24.18.06.35_veh-35_00016_03642, 0942e763807c536b]
  - [2021.06.07.12.01.13_veh-47_03622_03844, 11ac0cd68d2b52be]
  - [2021.06.08.18.59.48_veh-12_03766_03974, 12384a61bce55dfd]
  - [2021.06.08.17.36.50_veh-26_00639_01479, 13eeb0a3d27454cd]


```
Global seed set to 0
INFO:nuplan.planning.script.builders.main_callback_builder:Building MultiMainCallback...
INFO:nuplan.planning.script.builders.main_callback_builder:Building MultiMainCallback: 4...DONE!
2023-07-25 01:29:03,415 INFO {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/script/builders/worker_pool_builder.py:19}  Building WorkerPool...
2023-07-25 01:29:03,420 INFO {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/utils/multithreading/worker_pool.py:101}  Worker: SingleMachineParallelExecutor
2023-07-25 01:29:03,420 INFO {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/utils/multithreading/worker_pool.py:102}  Number of nodes: 1
Number of CPUs per node: 36
Number of GPUs per node: 0
Number of threads across all nodes: 36
Liu Shuijing (CR/RAS1-NA) at 7/24/2023 5:13 PM
2023-07-25 01:29:03,420 INFO {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/script/builders/worker_pool_builder.py:27}  Building WorkerPool...DONE!
2023-07-25 01:29:03,421 INFO {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/script/builders/folder_builder.py:32}  Building experiment folders...
2023-07-25 01:29:03,421 INFO {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/script/builders/folder_builder.py:35}

        Folder where all results are stored: /home/lis2syv/nuplan_exp/pdm/dummy1

2023-07-25 01:29:03,428 INFO {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/script/builders/folder_builder.py:70}  Building experiment folders...DONE!
2023-07-25 01:29:03,428 INFO {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/script/builders/simulation_callback_builder.py:52}  Building AbstractCallback...
2023-07-25 01:29:03,428 INFO {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/script/builders/simulation_callback_builder.py:68}  Building AbstractCallback: 0...DONE!
2023-07-25 01:29:03,428 INFO {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/script/builders/simulation_builder.py:47}  Building simulations...
2023-07-25 01:29:03,428 INFO {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/script/builders/simulation_builder.py:53}  Extracting scenarios...
2023-07-25 01:29:03,428 INFO {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/common/utils/distributed_scenario_filter.py:83}  Building Scenarios in mode DistributedMode.SINGLE_NODE
2023-07-25 01:29:03,429 INFO {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/script/builders/scenario_building_builder.py:18}  Building AbstractScenarioBuilder...
2023-07-25 01:29:03,453 INFO {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/script/builders/scenario_building_builder.py:24}  Building AbstractScenarioBuilder...DONE!
2023-07-25 01:29:03,453 INFO {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/script/builders/scenario_filter_builder.py:35}  Building ScenarioFilter...
2023-07-25 01:29:03,573 INFO {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/script/builders/scenario_filter_builder.py:44}  Building ScenarioFilter...DONE!
2023-07-25 01:29:29,230 INFO {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/script/builders/simulation_builder.py:74}  Building metric engines...
2023-07-25 01:29:29,511 INFO {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/script/builders/simulation_builder.py:76}  Building metric engines...DONE
2023-07-25 01:29:29,512 INFO {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/script/builders/simulation_builder.py:80}  Building simulations from 1118 scenarios...
2023-07-25 01:36:11,912 INFO {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/script/builders/simulation_builder.py:133}  Building simulations...DONE!
2023-07-25 01:36:11,913 INFO {/home/lis2syv/nuPlan/nuplan-devkit//nuplan/planning/script/run_simulation.py:78}  Running simulation...
2023-07-25 01:36:11,913 INFO {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/script/utils.py:138}  Executing runners...
2023-07-25 01:36:11,913 INFO {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/runner/executor.py:82}  Starting 1118 simulations using SingleMachineParallelExecutor!
2023-07-25 01:44:57,447 ERROR {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/metrics/metric_engine.py:118}  Running speed_limit_compliance with error:
2023-07-25 01:44:58,220 WARNING {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/runner/executor.py:32}  ----------- Simulation failed: with the following trace:
Traceback (most recent call last):
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/metrics/metric_engine.py", line 112, in compute_metric_results
    metric_results[metric.name] = metric.compute(history, scenario=scenario)
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/metrics/evaluation_metrics/common/speed_limit_compliance.py", line218, in compute
    time_series = TimeSeries(
  File "<string>", line 7, in __init__
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/metrics/metric_result.py", line 127, in __post_init__
    assert len(self.time_stamps) == len(self.values)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/runner/executor.py", line 27, in run_simulation
    return sim_runner.run()
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/runner/simulations_runner.py", line 128, in run
    self.simulation.callback.on_simulation_end(self.simulation.setup, self.planner, self.simulation.history)
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/callback/multi_callback.py", line 68, in on_simulation_end
    callback.on_simulation_end(setup, planner, history)
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/callback/metric_callback.py", line 102, in on_simulation_end
    run_metric_engine(
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/callback/metric_callback.py", line 24, in run_metric_engine
    metric_files = metric_engine.compute(history, scenario=scenario, planner_name=planner_name)
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/metrics/metric_engine.py", line 133, in compute
    all_metrics_results = self.compute_metric_results(history=history, scenario=scenario)
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/metrics/metric_engine.py", line 119, in compute_metric_results
    raise RuntimeError(f"Metric Engine failed with: {e}")
RuntimeError: Metric Engine failed with:
2023-07-25 01:44:58,221 WARNING {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/runner/executor.py:34}  Simulation failed with error:
 Metric Engine failed with:
2023-07-25 01:44:58,221 WARNING {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/runner/executor.py:38}
Failed simulation [log,token]:
[2021.07.24.23.59.52_veh-12_04767_05924, 05f93c480c1d5984]

2023-07-25 01:44:58,221 WARNING {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/runner/executor.py:40}  ----------- Simulation failed!
2023-07-25 01:45:25,891 ERROR {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/metrics/metric_engine.py:118}  Running speed_limit_compliance with error:
2023-07-25 01:45:25,892 WARNING {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/runner/executor.py:32}  ----------- Simulation failed: with the following trace:
Traceback (most recent call last):
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/metrics/metric_engine.py", line 112, in compute_metric_results
    metric_results[metric.name] = metric.compute(history, scenario=scenario)
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/metrics/evaluation_metrics/common/speed_limit_compliance.py", line218, in compute
    time_series = TimeSeries(
  File "<string>", line 7, in __init__
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/metrics/metric_result.py", line 127, in __post_init__
    assert len(self.time_stamps) == len(self.values)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/runner/executor.py", line 27, in run_simulation
    return sim_runner.run()
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/runner/simulations_runner.py", line 128, in run
    self.simulation.callback.on_simulation_end(self.simulation.setup, self.planner, self.simulation.history)
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/callback/multi_callback.py", line 68, in on_simulation_end
    callback.on_simulation_end(setup, planner, history)
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/callback/metric_callback.py", line 102, in on_simulation_end
    run_metric_engine(
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/callback/metric_callback.py", line 24, in run_metric_engine
    metric_files = metric_engine.compute(history, scenario=scenario, planner_name=planner_name)
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/metrics/metric_engine.py", line 133, in compute
    all_metrics_results = self.compute_metric_results(history=history, scenario=scenario)
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/metrics/metric_engine.py", line 119, in compute_metric_results
    raise RuntimeError(f"Metric Engine failed with: {e}")
RuntimeError: Metric Engine failed with:
2023-07-25 01:45:25,892 WARNING {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/runner/executor.py:34}  Simulation failed with error:
 Metric Engine failed with:
2023-07-25 01:45:25,892 WARNING {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/runner/executor.py:38}
Failed simulation [log,token]:
 [2021.07.24.00.36.59_veh-47_05600_06769, 011d97b0e5a85f5f]

2023-07-25 01:45:25,892 WARNING {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/runner/executor.py:40}  ----------- Simulation failed!
2023-07-25 01:53:19,915 ERROR {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/metrics/metric_engine.py:118}  Running drivable_area_compliance with error:
2023-07-25 01:53:20,233 WARNING {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/runner/executor.py:32}  ----------- Simulation failed: with the following trace:
Traceback (most recent call last):
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/metrics/metric_engine.py", line 112, in compute_metric_results
    metric_results[metric.name] = metric.compute(history, scenario=scenario)
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/metrics/evaluation_metrics/common/drivable_area_compliance.py", line 177, in compute
    time_series = TimeSeries(unit='boolean', time_stamps=list(time_stamps), values=corners_in_drivable_area)
  File "<string>", line 7, in __init__
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/metrics/metric_result.py", line 127, in __post_init__
    assert len(self.time_stamps) == len(self.values)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/runner/executor.py", line 27, in run_simulation
    return sim_runner.run()
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/runner/simulations_runner.py", line 128, in run
    self.simulation.callback.on_simulation_end(self.simulation.setup, self.planner, self.simulation.history)
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/callback/multi_callback.py", line 68, in on_simulation_end
    callback.on_simulation_end(setup, planner, history)
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/callback/metric_callback.py", line 102, in on_simulation_end
    run_metric_engine(
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/callback/metric_callback.py", line 24, in run_metric_engine
    metric_files = metric_engine.compute(history, scenario=scenario, planner_name=planner_name)
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/metrics/metric_engine.py", line 133, in compute
    all_metrics_results = self.compute_metric_results(history=history, scenario=scenario)
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/metrics/metric_engine.py", line 119, in compute_metric_results
    raise RuntimeError(f"Metric Engine failed with: {e}")
RuntimeError: Metric Engine failed with:
2023-07-25 01:53:20,294 WARNING {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/runner/executor.py:34}  Simulation failed with error:
 Metric Engine failed with:
2023-07-25 01:53:20,295 WARNING {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/runner/executor.py:38}
Failed simulation [log,token]:
 [2021.07.24.18.06.35_veh-35_00016_03642, 0942e763807c536b]

2023-07-25 01:53:20,295 WARNING {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/runner/executor.py:40}  ----------- Simulation failed!
2023-07-25 02:02:38,561 ERROR {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/metrics/metric_engine.py:118}  Running drivable_area_compliance with error:
2023-07-25 02:02:38,644 WARNING {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/runner/executor.py:32}  ----------- Simulation failed: with the following trace:
Traceback (most recent call last):
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/metrics/metric_engine.py", line 112, in compute_metric_results
    metric_results[metric.name] = metric.compute(history, scenario=scenario)
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/metrics/evaluation_metrics/common/drivable_area_compliance.py", line 177, in compute
    time_series = TimeSeries(unit='boolean', time_stamps=list(time_stamps), values=corners_in_drivable_area)
  File "<string>", line 7, in __init__
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/metrics/metric_result.py", line 127, in __post_init__
    assert len(self.time_stamps) == len(self.values)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/runner/executor.py", line 27, in run_simulation
    return sim_runner.run()
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/runner/simulations_runner.py", line 128, in run
    self.simulation.callback.on_simulation_end(self.simulation.setup, self.planner, self.simulation.history)
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/callback/multi_callback.py", line 68, in on_simulation_end
    callback.on_simulation_end(setup, planner, history)
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/callback/metric_callback.py", line 102, in on_simulation_end
    run_metric_engine(
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/callback/metric_callback.py", line 24, in run_metric_engine
    metric_files = metric_engine.compute(history, scenario=scenario, planner_name=planner_name)
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/metrics/metric_engine.py", line 133, in compute
    all_metrics_results = self.compute_metric_results(history=history, scenario=scenario)
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/metrics/metric_engine.py", line 119, in compute_metric_results
    raise RuntimeError(f"Metric Engine failed with: {e}")
RuntimeError: Metric Engine failed with:
2023-07-25 02:02:38,766 WARNING {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/runner/executor.py:34}  Simulation failed with error:
 Metric Engine failed with:
2023-07-25 02:02:38,965 WARNING {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/runner/executor.py:38}
Failed simulation [log,token]:
 [2021.06.07.12.01.13_veh-47_03622_03844, 11ac0cd68d2b52be]

2023-07-25 02:02:38,965 WARNING {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/runner/executor.py:40}  ----------- Simulation failed!
2023-07-25 02:04:31,987 ERROR {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/metrics/metric_engine.py:118}  Running speed_limit_compliance with error:
2023-07-25 02:04:31,988 WARNING {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/runner/executor.py:32}  ----------- Simulation failed: with the following trace:
Traceback (most recent call last):
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/metrics/metric_engine.py", line 112, in compute_metric_results
    metric_results[metric.name] = metric.compute(history, scenario=scenario)
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/metrics/evaluation_metrics/common/speed_limit_compliance.py", line218, in compute
    time_series = TimeSeries(
  File "<string>", line 7, in __init__
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/metrics/metric_result.py", line 127, in __post_init__
    assert len(self.time_stamps) == len(self.values)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/runner/executor.py", line 27, in run_simulation
    return sim_runner.run()
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/runner/simulations_runner.py", line 128, in run
    self.simulation.callback.on_simulation_end(self.simulation.setup, self.planner, self.simulation.history)
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/callback/multi_callback.py", line 68, in on_simulation_end
    callback.on_simulation_end(setup, planner, history)
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/callback/metric_callback.py", line 102, in on_simulation_end
    run_metric_engine(
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/callback/metric_callback.py", line 24, in run_metric_engine
    metric_files = metric_engine.compute(history, scenario=scenario, planner_name=planner_name)
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/metrics/metric_engine.py", line 133, in compute
    all_metrics_results = self.compute_metric_results(history=history, scenario=scenario)
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/metrics/metric_engine.py", line 119, in compute_metric_results
    raise RuntimeError(f"Metric Engine failed with: {e}")
RuntimeError: Metric Engine failed with:
2023-07-25 02:04:31,988 WARNING {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/runner/executor.py:34}  Simulation failed with error:
 Metric Engine failed with:
2023-07-25 02:04:31,988 WARNING {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/runner/executor.py:38}
Failed simulation [log,token]:
 [2021.06.08.18.59.48_veh-12_03766_03974, 12384a61bce55dfd]

2023-07-25 02:04:31,988 WARNING {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/runner/executor.py:40}  ----------- Simulation failed!
2023-07-25 02:05:46,282 ERROR {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/metrics/metric_engine.py:118}  Running drivable_area_compliance with error:
2023-07-25 02:05:46,283 WARNING {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/runner/executor.py:32}  ----------- Simulation failed: with the following trace:
Traceback (most recent call last):
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/metrics/metric_engine.py", line 112, in compute_metric_results
    metric_results[metric.name] = metric.compute(history, scenario=scenario)
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/metrics/evaluation_metrics/common/drivable_area_compliance.py", line 177, in compute
    time_series = TimeSeries(unit='boolean', time_stamps=list(time_stamps), values=corners_in_drivable_area)
  File "<string>", line 7, in __init__
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/metrics/metric_result.py", line 127, in __post_init__
    assert len(self.time_stamps) == len(self.values)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/runner/executor.py", line 27, in run_simulation
    return sim_runner.run()
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/runner/simulations_runner.py", line 128, in run
    self.simulation.callback.on_simulation_end(self.simulation.setup, self.planner, self.simulation.history)
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/callback/multi_callback.py", line 68, in on_simulation_end
    callback.on_simulation_end(setup, planner, history)
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/callback/metric_callback.py", line 102, in on_simulation_end
    run_metric_engine(
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/callback/metric_callback.py", line 24, in run_metric_engine
    metric_files = metric_engine.compute(history, scenario=scenario, planner_name=planner_name)
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/metrics/metric_engine.py", line 133, in compute
    all_metrics_results = self.compute_metric_results(history=history, scenario=scenario)
  File "/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/metrics/metric_engine.py", line 119, in compute_metric_results
    raise RuntimeError(f"Metric Engine failed with: {e}")
RuntimeError: Metric Engine failed with:
2023-07-25 02:05:46,283 WARNING {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/runner/executor.py:34}  Simulation failed with error:
 Metric Engine failed with:
2023-07-25 02:05:46,283 WARNING {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/runner/executor.py:38}
Failed simulation [log,token]:
 [2021.06.08.17.36.50_veh-26_00639_01479, 13eeb0a3d27454cd]

2023-07-25 02:05:46,283 WARNING {/home/lis2syv/nuPlan/nuplan-devkit/nuplan/planning/simulation/runner/executor.py:40}  ----------- Simulation failed!
```

**Comment by mh0797** [comment] 2023-07-28 12:12
Hi @Shuijing725 ,

On my side, the error only occurs when using the `single_machine_thread_pool` worker.
Everything works as expected with `worker=ray_distributed`. Can you briefly confirm that?

If so, changing the worker is a simple workaround. Nonetheless, we will investigate this further.

**Comment by mh0797** [comment] 2023-07-28 13:22
Hi @Shuijing725.

I could reproduce the issue also with the `simple_planner` and the `log_future_planner` of nuPlan.
Hence, this is not caused by our PDM Model.
Please consider opening an issue for the [nuplan-devkit](https://github.com/motional/nuplan-devkit/issues).

As mentioned above, you can circumvent this for now by using `worker=ray_distributed`.

With that being said, I am closing this issue.

**Closed as completed by mh0797** 2023-07-28 13:22 UTC
