### ISSUE TITLE
Issue eveluating

### ISSUE THREAD

**Issue by tom-bou** [autonomousvision/tuplan_garage#45] opened 2024-05-24 21:28 UTC
While running
```
SPLIT=mini_test_split
CHALLENGE=closed_loop_reactive_agents # open_loop_boxes, closed_loop_nonreactive_agents, closed_loop_reactive_agents
CHECKPOINT=~/tuplan_garage/pdm_open_checkpoint.ckpt

taskset -c 0-30 python $NUPLAN_DEVKIT_ROOT/nuplan/planning/script/run_simulation.py \
+simulation=$CHALLENGE \
planner=pdm_open_planner \
planner.pdm_open_planner.checkpoint_path=$CHECKPOINT \
scenario_filter=$SPLIT \
scenario_builder=nuplan \
hydra.searchpath="[pkg://tuplan_garage.planning.script.config.common, pkg://tuplan_garage.planning.script.config.simulation, pkg://nuplan.planning.script.config.common, pkg://nuplan.planning.script.experiments]" \
```

on a cluster i've gotten the issue
```

(wrapped_fn pid=3822105) Before assert: _drivable_area_map = <tuplan_garage.planning.simulation.planner.pdm_planner.observation.pdm_occupancy_map.PDMOccupancyMap object at 0x7f996e5255b0> [repeated 27x across cluster]
(wrapped_fn pid=3822105) Drivable area map has 'intersects' method. [repeated 21x across cluster]
(wrapped_fn pid=3822105) Test intersecting lanes at (0,0): [] [repeated 21x across cluster]
(wrapped_fn pid=3822105) Intersecting lanes at ego position [ 664863.43947442 3999616.06394007]: ['63253'] [repeated 18x across cluster]
(wrapped_fn pid=3822105) [] [repeated 5x across cluster]
(wrapped_fn pid=3822445) Intersecting lanes at ego position [ 664430.74693994 3998337.4457144 ]: ['63319']
Converting detections to smart agents:   0%|          | 0/17 [00:00<?, ?it/s] [repeated 5x across cluster]
                                                                                      [repeated 7x across cluster]
(wrapped_fn pid=3822105) WARNING:nuplan.planning.simulation.runner.executor:----------- Simulation failed: with the following trace: [repeated 5x across cluster]
(wrapped_fn pid=3822105) Traceback (most recent call last): [repeated 5x across cluster]
(wrapped_fn pid=3822105)   File "/home/tombo/nuplan-devkit/nuplan/planning/simulation/runner/executor.py", line 27, in run_simulation [repeated 5x across cluster]
(wrapped_fn pid=3822105)     return sim_runner.run() [repeated 5x across cluster]
(wrapped_fn pid=3822105)   File "/home/tombo/nuplan-devkit/nuplan/planning/simulation/runner/simulations_runner.py", line 113, in run [repeated 5x across cluster]
(wrapped_fn pid=3822105)     trajectory = self.planner.compute_trajectory(planner_input) [repeated 5x across cluster]
(wrapped_fn pid=3822105)   File "/home/tombo/nuplan-devkit/nuplan/planning/simulation/planner/abstract_planner.py", line 105, in compute_trajectory [repeated 10x across cluster]
(wrapped_fn pid=3822105)     raise e [repeated 5x across cluster]
(wrapped_fn pid=3822105)     trajectory = self.compute_planner_trajectory(current_input) [repeated 5x across cluster]
(wrapped_fn pid=3822105)   File "/home/tombo/tuplan_garage/tuplan_garage/planning/simulation/planner/pdm_planner/pdm_open_planner.py", line 109, in compute_planner_trajectory [repeated 5x across cluster]
(wrapped_fn pid=3822105)     current_lane = self._get_starting_lane(ego_state) [repeated 5x across cluster]
(wrapped_fn pid=3822105)   File "/home/tombo/tuplan_garage/tuplan_garage/planning/simulation/planner/pdm_planner/abstract_pdm_planner.py", line 123, in _get_starting_lane [repeated 5x across cluster]
(wrapped_fn pid=3822105)     on_route_lanes, heading_error = self._get_intersecting_lanes(ego_state) [repeated 5x across cluster]
(wrapped_fn pid=3822105)   File "/home/tombo/tuplan_garage/tuplan_garage/planning/simulation/planner/pdm_planner/abstract_pdm_planner.py", line 158, in _get_intersecting_lanes [repeated 5x across cluster]
(wrapped_fn pid=3822105)     assert ( [repeated 5x across cluster]
(wrapped_fn pid=3822105) AssertionError: AbstractPDMPlanner: Drivable area map must be initialized first! [repeated 5x across cluster]
(wrapped_fn pid=3822105) WARNING:nuplan.planning.simulation.runner.executor:Simulation failed with error: [repeated 5x across cluster]
(wrapped_fn pid=3822105)  AbstractPDMPlanner: Drivable area map must be initialized first! [repeated 5x across cluster]
(wrapped_fn pid=3822105) WARNING:nuplan.planning.simulation.runner.executor: [repeated 5x across cluster]
(wrapped_fn pid=3822105) Failed simulation [log,token]: [repeated 5x across cluster]
(wrapped_fn pid=3822105)  [repeated 13x across cluster]
(wrapped_fn pid=3822105) WARNING:nuplan.planning.simulation.runner.executor:----------- Simulation failed! [repeated 5x across cluster]
```

**Comment by DanielDauner** [comment] 2024-05-25 13:02
The drivable area map (an occupancy map used to find the initial lane) hasn't been initialized. Have you made any changes to the code?

**Comment by tom-bou** [comment] 2024-05-26 14:34
> The drivable area map (an occupancy map used to find the initial lane) hasn't been initialized. Have you made any changes to the code?

No i haven't made any changes

**Comment by DanielDauner** [comment] 2024-05-26 18:58
Hi, I am unable to reproduce your issue. 

- What scenario filter are you using? (`mini_test_split` is not part of nuplan-devkit or tuplan garage).
- Are you having the same issue on a local installation or only on the cluster?
- Please make sure the drivable area map is initialized, as done [here](https://github.com/autonomousvision/tuplan_garage/blob/main/tuplan_garage/planning/simulation/planner/pdm_planner/pdm_open_planner.py#L103).

Try running your code with `RAY_DEDUP_LOGS=0` to see the error traceback without summarized repetition of ray.

**Comment by DanielDauner** [comment] 2024-05-30 16:21
I'm closing it for now. Feel free to re-open it if this issue persists.

**Closed as completed by DanielDauner** 2024-05-30 16:21 UTC
